version: '0.0.1-{build}'

platform: Any CPU
configuration: Release
os: Visual Studio 2019

before_build:
  - dotnet restore  

build:
  parallel: true            
  project: TheTruth.sln
  
after_build:
  - dotnet pack ".\TheTruth.DataAnnotation\TheTruth.DataAnnotation.csproj" -c Release -o artifacts
artifacts:
  - path: artifacts\**\*.*
cache:
  - '%USERPROFILE%\.nuget\packages'
deploy:
  provider: NuGet
  api_key:
    secure: uqd0RkPv0vZ8gCfUD0MylWDv0kqJMGOq2GEfMyb4298a1O54we2pR3U0cNvtQMOr
  skip_symbols: false
  artifact: /.*\.nupkg/
